---
title: "Poder Executivo Federal: Taxa de Reposição de Servidores"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: bootstrap
---


```{r setup, include=FALSE}
library(flexdashboard)
library(scales)

dados <- readr::read_csv2("../data-raw/Desp_ativos.csv") |> 
  janitor::clean_names()  |> dplyr::mutate(
    Ano = as.factor(ano)  
  )|>
  dplyr::rename(`Servidores Ativos` = ativos, 
                `Desp. Liquidada (R$ Bi)` = desp_liq)
   


```

```{r}

library(echarts4r)
dados |> 
  echarts4r::e_charts(Ano) |> 
  echarts4r::e_bar(serie = `Desp. Liquidada (R$ Bi)`) |> 
  echarts4r::e_line(`Servidores Ativos`, y_index = 1) |>  # add secondary axis
  echarts4r::e_y_axis(formatter = e_axis_formatter(style = "currency")) |> 
  e_format_y_axis(
    suffix = "",
    prefix = "R$")|>

  e_locale("PT-br") |>
  e_y_axis(formatter = e_axis_formatter(style = "decimal", digits = 3), index = 1) |>
  echarts4r::e_title("Servidores x Despesas", "Poder Executivo Federal") |>  # Add title & subtitle
  echarts4r::e_theme_custom('{"color":["#004580","#ef0219"]}') |>  # theme
  echarts4r::e_legend(right = 0) |>  # move legend to the bottom
  echarts4r::e_tooltip(trigger = "axis") # tooltip
  
  

```


